version: '2'
services:
  redis:
    image: redis
    restart: always
  mongo:
    image: mongo
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    volumes:
      - ./mongodbdata:/data/db
    restart: always
  app:
    build: .
    ports:
      - 3000:3000
    links:
      - redis:redis
      - mongo:mongo
    depends_on:
      - mongo
    restart: always

