version: '2'
services:
  redis:
    image: redis
    restart: always
  mongo:
    image: mongo
    restart: always
  app:
    build: .
    ports:
      - 3000:3000
    links:
      - redis:redis
      - mongo:mongo
    restart: always

